export const categories = {
  animals: {
    name: 'Animals',
    icon: '🦁',
    clues: [
      { word: 'ELEPHANT', clue: 'Largest land animal with a trunk', direction: 'across' },
      { word: 'GIRAFFE', clue: 'Tallest animal with a long neck', direction: 'across' },
      { word: 'ZEBRA', clue: 'African animal with black and white stripes', direction: 'across' },
      { word: 'PENGUIN', clue: 'Flightless bird from Antarctica', direction: 'across' },
      { word: 'DOLPHIN', clue: 'Marine mammal known for intelligence', direction: 'down' },
      { word: 'TIGER', clue: 'Big cat with orange fur and stripes', direction: 'down' },
      { word: 'LION', clue: 'King of the jungle', direction: 'down' },
      { word: 'WHALE', clue: 'Largest animal that lives in the ocean', direction: 'down' },
    ],
  },
  fruits: {
    name: 'Fruits',
    icon: '🍎',
    clues: [
      { word: 'BANANA', clue: 'Yellow tropical fruit', direction: 'across' },
      { word: 'STRAWBERRY', clue: 'Red berry with tiny seeds', direction: 'across' },
      { word: 'ORANGE', clue: 'Citrus fruit, orange in color', direction: 'across' },
      { word: 'GRAPE', clue: 'Small purple or green fruit in bunches', direction: 'across' },
      { word: 'APPLE', clue: 'Red or green fruit, keeps doctor away', direction: 'down' },
      { word: 'MANGO', clue: 'King of fruits, tropical sweet fruit', direction: 'down' },
      { word: 'WATERMELON', clue: 'Summer fruit, green outside red inside', direction: 'down' },
      { word: 'PINEAPPLE', clue: 'Spiky tropical fruit with yellow flesh', direction: 'down' },
    ],
  },
  vegetables: {
    name: 'Vegetables',
    icon: '🥬',
    clues: [
      { word: 'CARROT', clue: 'Orange root vegetable', direction: 'across' },
      { word: 'BROCCOLI', clue: 'Green vegetable that looks like a tree', direction: 'across' },
      { word: 'TOMATO', clue: 'Red juicy vegetable used in salads', direction: 'across' },
      { word: 'SPINACH', clue: 'Leafy green vegetable, Popeyes favorite', direction: 'across' },
      { word: 'POTATO', clue: 'Starchy root vegetable', direction: 'down' },
      { word: 'ONION', clue: 'Vegetable that makes you cry', direction: 'down' },
      { word: 'CUCUMBER', clue: 'Long green vegetable', direction: 'down' },
      { word: 'PEPPER', clue: 'Colorful vegetable, can be red or green', direction: 'down' },
    ],
  },
  places: {
    name: 'Places',
    icon: '🏛️',
    clues: [
      { word: 'LIBRARY', clue: 'Place where books are kept', direction: 'across' },
      { word: 'HOSPITAL', clue: 'Place where sick people get treatment', direction: 'across' },
      { word: 'MUSEUM', clue: 'Place to see art and historical artifacts', direction: 'across' },
      { word: 'CINEMA', clue: 'Place where movies are shown', direction: 'across' },
      { word: 'AIRPORT', clue: 'Place where airplanes take off', direction: 'down' },
      { word: 'SCHOOL', clue: 'Place where students learn', direction: 'down' },
      { word: 'MARKET', clue: 'Place where groceries are sold', direction: 'down' },
      { word: 'TEMPLE', clue: 'Place of worship', direction: 'down' },
    ],
  },
  countries: {
    name: 'Countries',
    icon: '🌍',
    clues: [
      { word: 'JAPAN', clue: 'Island nation in East Asia known for cherry blossoms', direction: 'across' },
      { word: 'BRAZIL', clue: 'Country in South America famous for Amazon', direction: 'across' },
      { word: 'FRANCE', clue: 'European country famous for Eiffel Tower', direction: 'across' },
      { word: 'AUSTRALIA', clue: 'Country known for kangaroos and koalas', direction: 'across' },
      { word: 'CANADA', clue: 'North American country with Niagara Falls', direction: 'down' },
      { word: 'INDIA', clue: 'Asian country famous for Taj Mahal', direction: 'down' },
      { word: 'EGYPT', clue: 'Country with great pyramids', direction: 'down' },
      { word: 'SPAIN', clue: 'European country with flamenco dancing', direction: 'down' },
    ],
  },
  things: {
    name: 'Things',
    icon: '🎁',
    clues: [
      { word: 'BICYCLE', clue: 'Two-wheeled vehicle', direction: 'across' },
      { word: 'UMBRELLA', clue: 'Used for protection from rain', direction: 'across' },
      { word: 'CAMERA', clue: 'Device to take photographs', direction: 'across' },
      { word: 'TELESCOPE', clue: 'Device to see stars and planets', direction: 'across' },
      { word: 'LAMP', clue: 'Device that provides light', direction: 'down' },
      { word: 'CLOCK', clue: 'Shows time of day', direction: 'down' },
      { word: 'WATCH', clue: 'Wearable timepiece', direction: 'down' },
      { word: 'GUITAR', clue: 'Musical instrument with strings', direction: 'down' },
    ],
  },
};
